name: Allowlist pool

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Network
        required: true
        options:
          - avalanche
          - arbitrum
          - base
          - ethereum
          - gnosis-chain
          - goerli
          - polygon
          - optimism
          - zkevm
      poolType:
        type: choice
        description: Pool Type
        required: true
        options:
          - Weighted
          - Stable
      poolId:
        type: string
        description: Pool ID
        required: true
      poolDescription:
        type: string
        description: Pool Description
        required: false

jobs:
  allowlist-pool:
    uses: ./.github/workflows/allowlist.yml
    with:
      network: ${{ github.event.inputs.network }}
      poolType: ${{ github.event.inputs.poolType }}
      poolId: ${{ github.event.inputs.poolId }}
      poolDescription: ${{ github.event.inputs.poolDescription }}
